package HibernateSisGesIncidenciasPOJOs;
// Generated 06-nov-2016 16:12:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private String username;
     private String password;
     private String nombreCompleto;
     private String telefono;
     private Set historials = new HashSet(0);
     private Set incidenciasesForOrigen = new HashSet(0);
     private Set incidenciasesForDestino = new HashSet(0);

    public Empleados() {
    }

    public Empleados(String username, String password) {
        this.username = username;
        this.password = password;
    }

	
    public Empleados(String username, String password, String nombreCompleto, String telefono) {
        this.username = username;
        this.password = password;
        this.nombreCompleto = nombreCompleto;
        this.telefono = telefono;
    }
    public Empleados(String username, String password, String nombreCompleto, String telefono, Set historials, Set incidenciasesForOrigen, Set incidenciasesForDestino) {
       this.username = username;
       this.password = password;
       this.nombreCompleto = nombreCompleto;
       this.telefono = telefono;
       this.historials = historials;
       this.incidenciasesForOrigen = incidenciasesForOrigen;
       this.incidenciasesForDestino = incidenciasesForDestino;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set historials) {
        this.historials = historials;
    }
    public Set getIncidenciasesForOrigen() {
        return this.incidenciasesForOrigen;
    }
    
    public void setIncidenciasesForOrigen(Set incidenciasesForOrigen) {
        this.incidenciasesForOrigen = incidenciasesForOrigen;
    }
    public Set getIncidenciasesForDestino() {
        return this.incidenciasesForDestino;
    }
    
    public void setIncidenciasesForDestino(Set incidenciasesForDestino) {
        this.incidenciasesForDestino = incidenciasesForDestino;
    }

    @Override
    public String toString() {
        return "Empleados{" + "username=" + username + ", password=" + password + ", nombreCompleto=" + nombreCompleto + ", telefono=" + telefono + ", historials=" + historials + ", incidenciasesForOrigen=" + incidenciasesForOrigen + ", incidenciasesForDestino=" + incidenciasesForDestino + '}';
    }




}


