package HibernateSisGesIncidenciasPOJOs;
// Generated 06-nov-2016 16:12:52 by Hibernate Tools 4.3.1



/**
 * Incidencias generated by hbm2java
 */
public class Incidencias  implements java.io.Serializable {


     private Integer idIncidencia;
     private Empleados empleadosByOrigen;
     private Empleados empleadosByDestino;
     private String fechaHora;
     private String tipo;
     private String detalle;

    public Incidencias() {
    }

    public Incidencias(Integer idIncidencia) {
        this.idIncidencia = idIncidencia;
    }

    public Incidencias(Empleados empleadosByOrigen, Empleados empleadosByDestino, String fechaHora, String tipo, String detalle) {
       this.empleadosByOrigen = empleadosByOrigen;
       this.empleadosByDestino = empleadosByDestino;
       this.fechaHora = fechaHora;
       this.tipo = tipo;
       this.detalle = detalle;
    }
   
    public Integer getIdIncidencia() {
        return this.idIncidencia;
    }
    
    public void setIdIncidencia(Integer idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public Empleados getEmpleadosByOrigen() {
        return this.empleadosByOrigen;
    }
    
    public void setEmpleadosByOrigen(Empleados empleadosByOrigen) {
        this.empleadosByOrigen = empleadosByOrigen;
    }
    public Empleados getEmpleadosByDestino() {
        return this.empleadosByDestino;
    }
    
    public void setEmpleadosByDestino(Empleados empleadosByDestino) {
        this.empleadosByDestino = empleadosByDestino;
    }
    public String getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(String fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    @Override
    public String toString() {
        return "Incidencias{" + "idIncidencia=" + idIncidencia + ", empleadosByOrigen=" + empleadosByOrigen + ", empleadosByDestino=" + empleadosByDestino + ", fechaHora=" + fechaHora + ", tipo=" + tipo + ", detalle=" + detalle + '}';
    }






}


